//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmertexBusTicketsSystem.BL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<int> Id_SpecifiedVoyage { get; set; }
        public Nullable<int> Id_Status { get; set; }
        public Nullable<int> Id_Passenger { get; set; }
        public string info { get; set; }
        public Nullable<int> Id_Order { get; set; }
        public string Id_User { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Passenger Passenger { get; set; }
        public virtual SpecifiedVoyage SpecifiedVoyage { get; set; }
        public virtual TicketStatus TicketStatus { get; set; }
    }
}
